apiVersion: v2
name: devx-helloworld-springboot-test-d8fcr
description: Chart for creating devx-helloworld-springboot-test-d8fcr and ingress mapping our Flexport EKS clusters

type: application
version: 0.1.0
